library(tidyverse)
library(rstan)
library(shinystan)
rm(list=ls())
##read in a description of the stim and produce calcobs.df and ordobs.df for consumption by obsinput.stan

stim.df <- read.csv("sandpitstim.csv") #input generated by triangles.js in stimdemo with display_as set to "csv"

stim.df$stimid <- as.character(stim.df$stimid)
stim.df$trialid <- 1:nrow(stim.df)
##you're going to want the shape-matching info, but it's annoyingly tacked on as the last three chars of stimid.
for(i in 1:nrow(stim.df)){
    stim.df$shapetype1[i] <- substr(stim.df$stimid[i],nchar(stim.df$stimid[i])-2,nchar(stim.df$stimid[i])-2)
    stim.df$shapetype2[i] <- substr(stim.df$stimid[i],nchar(stim.df$stimid[i])-1,nchar(stim.df$stimid[i])-1)
    stim.df$shapetype3[i] <- substr(stim.df$stimid[i],nchar(stim.df$stimid[i]),nchar(stim.df$stimid[i]))
}

##THESE ARE ALL totally BOGUS  GUESSnumbers!
basenoise = 250 #these are on triangle area scale now.
ord_basenoise = basenoise
orientation_ordpenalty = basenoise/2
shapetype_ordpenalty = basenoise/2
tolerance = basenoise/2 

calcobs.df = data.frame(trialid=c(),optionid=c(),value=c(),noisesd=c())
ordobs.df = data.frame(trialid=c(),option1=c(),option2=c(),attribute=c(),value=c(),noisesd=c(),tolerance=c())

##calculation observations:
for(i in 1:nrow(stim.df)){
    for(anoption in 1:3){
        calcobs.df <- rbind(calcobs.df,data.frame(
                                           trialid=i,
                                           optionid=anoption,
                                           value=stim.df[i,paste0("area",anoption)],
                                           noisesd=basenoise
                                       )
                            )
    }
}

#work out what the height and width attributes are: this is kinda problematic. Is it short and long axes of the triangle that are being compared, or the vertical and orizontal dimensions? The confusion is kinda the point of the study... but it's still confusing.
for(i in 1:nrow(stim.df)){
    for(anoption in 1:3){
        if(stim.df[i,paste0("orientation",anoption)]%in%c(0,2)){ ##NS orientations
            stim.df[i,paste0("height",anoption)] <- stim.df[i,paste0("axislength",anoption)]
            stim.df[i,paste0("width",anoption)] <- stim.df[i,paste0("base",anoption)]
            
        }else{##EW orientations
            stim.df[i,paste0("height",anoption)] <- stim.df[i,paste0("base",anoption)]
            stim.df[i,paste0("width",anoption)] <- stim.df[i,paste0("axislength",anoption)]
        }
    }
}

##ordinal observations
for(atrial in 1:nrow(stim.df)){   
    for(option1 in 2:3){#to hit the lower triangle only
        for(option2 in 1:(option1-1)){
            for(anattribute in c("height","width")){

                ordobs.df <- rbind(ordobs.df,data.frame(
                                                 trialid=atrial,
                                                 option1=option1,
                                                 option2=option2,
                                                 attribute=anattribute,
                                                 value=stim.df[atrial,paste0(anattribute,option1)]-stim.df[atrial,paste0(anattribute,option2)],
                                                 noisesd=ord_basenoise,#PLUS whatever incompatibility penalties there are? This is the whole point
                                                 tolerance=tolerance 
                                             )
                                   )
            }
        }
    }
}
ordobs.df$ord_status <- with(ordobs.df,ifelse(abs(value)<tolerance,2,ifelse(value<0,1,3)))

rm(list=setdiff(ls(),c("calcobs.df","ordobs.df","stim.df")))
save.image("calc_ord_obsdfs.RData")
